language: node_js
sudo: required
services:
  - docker

before_install:
  - docker build -t tosingh54/docker-react -f Dockerfile.dev .

script:
  - docker run tosingh54/docker-react npm test -- --coverage
